- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      # - at
      # - colordiff
      - curl
      # - htop
      # - iotop
      # - lsof
      # - mc
      # - mosh
      # - ncdu
      # - neofetch
      # - net-tools
      - nmap
      - screen
      # - sshfs
      - wget
      - whois
      # - zsh